baseURL = "/"
languageCode = "en-us"
title = "gomplate documentation"
theme = "hugo-material-docs"
googleAnalytics = "UA-82637990-3"

[params]
  author = "hairyhenderson"
  description = "gomplate documentation"
  copyright = "Released under the MIT license"
  provider = "GitHub"
  repo_url = "https://github.com/hairyhenderson/gomplate"
  logo = "images/gomplate-icon.svg"
  favicon = "favicon.ico"
  custom_css = [
    "stylesheets/search.css",
    "stylesheets/custom-palettes.css",
  ]
  custom_js = [
    "https://code.jquery.com/jquery-3.3.1.min.js",
    "https://cdnjs.cloudflare.com/ajax/libs/fuse.js/3.4.4/fuse.min.js",
    "https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js",
    "js/search.js"
  ]

[params.palette]
  primary = "spalding-gray"
  accent = "spalding-blue"

[social]
  twitter = "hairyhenderson"
  github  = "hairyhenderson"

[outputs]
  home = ["HTML", "RSS", "JSON"]
