name: 'Stale issue handler'
on:
  workflow_dispatch:
  issue_comment:
  schedule:
    - cron: '42 04 * * *'

permissions:
  issues: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v10
        # See https://github.com/actions/stale#all-options
        with:
          exempt-all-milestones: true
          days-before-stale: 60
          days-before-close: 14
          stale-issue-message: |
            This issue is stale because it has been open for 60 days with no
            activity. If it is no longer relevant or necessary, please close it.
            Given no action, it will be closed in 14 days.

            If it's still relevant, one of the following will remove the stale
            marking:
            - A maintainer can add this issue to a milestone to indicate that
                it's been accepted and will be worked on
            - A maintainer can remove the `stale` label
            - Anyone can post an update or other comment
          stale-pr-message: |
            This pull request is stale because it has been open for 60 days with
            no activity. If it is no longer relevant or necessary, please close
            it. Given no action, it will be closed in 14 days.

            If it's still relevant, one of the following will remove the stale
            marking:
            - A maintainer can add this pull request to a milestone to indicate
                that it's been accepted and will be worked on
            - A maintainer can remove the `stale` label
            - Anyone can post an update or other comment
            - Anyone with write access can push a commit to the pull request
                branch
